version: "3"

services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "19000:19000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend # Create backend container

  backend:
    # Create backend container
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
    links:
      - db # Create database container

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=username_goes_here
      - POSTGRES_PASSWORD=password_goes_here
    ports:
      - "5432:5432"
    container_name: database-docker
